export const login = async (req, res) => {
    try {

    } catch (err) {

    }
}

export const signUp = async (req, res) => {
    try {

    } catch (err) {

    }
}